### ISSUE TITLE
Stopped working after final v6 😭 

### ISSUE THREAD

**Issue by roanrobersson** [akursat/react-router-example#1]
Now on v6 final, the <PrivateRoute> never is called, only the element inside element={}

```javascript
<Routes>
	<PrivateRoute path="dashboard" element={<Dashboard />} roles={[ROLE.ADMIN]} />
	<PrivateRoute path="users" element={<Users />} roles={[ROLE.ADMIN, ROLE.USER]} />
	<Route path="/" element={<Home />} />
	<Route path="*" element={<NotFound />} />
</Routes>
```

Do you have any solution for this? 🙏

**Comment by auwtch** [comment]
I think this is the only way to do it "right" https://reactrouter.com/docs/en/v6/examples/auth

**Comment by akursat** [comment]
@roanrobersson I've upgraded example to to v6.0.2.
